cart/urls.py
from django.urls import path
from .views import cart_view, cart_update_view, cart_add_view, cart_delete_view, cart_clear_view, comment_update_view

urlpatterns = [
    path('', cart_view, name='cart_view'),
    path('add/', cart_add_view, name='cart_add'),
    path('update/', cart_update_view, name='cart_update'),
    path('delete/', cart_delete_view, name='cart_delete'),
    path('clear/', cart_clear_view, name='cart_clear'),
    path('comment_update/', comment_update_view, name='cart_comment_update'),
]

source/urls.py
from django.contrib import admin
from django.urls import path, include
from my_shop.views.category_views import IndexView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='home_page'),
    path('products/', include('my_shop.urls.product_urls')),
    path('categories/', include('my_shop.urls.category_urls')),
    path('favorites/', include('my_shop.urls.favorite_urls')),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
    path('payments/', include('payments.urls')),
    path('api/', include('my_shop_api.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

my_shop/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False, verbose_name='category_name')
    description = models.TextField(max_length=100, null=True, blank=True, verbose_name='description')
    picture = models.CharField(max_length=100, null=True, blank=True, verbose_name='picture')
    def __str__(self):
        return self.name
    

class Product(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False, verbose_name='product_name')
    description = models.TextField(max_length=350, null=True, blank=True, verbose_name='description')
    picture = models.CharField(max_length=100, null=True, blank=True, verbose_name='picture')
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00, verbose_name='price')
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE, related_name='products', null=False, verbose_name='category')
    created_at = models.DateTimeField(auto_now_add = True, verbose_name='created_at')
    quontity = models.IntegerField(null=True, blank=True, verbose_name='Quontity')
    seller = models.ForeignKey(get_user_model(), related_name='products', on_delete = models.CASCADE, null=True, verbose_name='Seller')

    def __str__(self):
        return f'#{self.pk} {self.name}'
    
    def get_absolute_url(self):
        return reverse('product_details', kwargs={'pk': self.pk})
    

templates/partials/carousel.html
<!-- ___________Carousel___________ -->
{% load static %}
<div class="container_fluid my_carousel d-none d-sm-block">
    <div id="carouselExampleIndicators" class="carousel slide carousel-fade" data-bs-ride="carousel" data-bs-interval="5000">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="{% static 'laptop-1205256_960_720.jpg' %}" class="d-block w-100" alt="carousel1">
        </div>
        <div class="carousel-item">
          <img src="{% static 'banner_sale.png' %}" class="d-block w-100" alt="carousel2">
        </div>
        <div class="carousel-item">
          <img src="{% static '3455180.jpg' %}" class="d-block w-100" alt="carousel3">
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>    
</div>

templates/partials/create_update_form.html
{% csrf_token %}

<div class="mb-3">
    {% for error in form.non_field_errors %}
        <p class="form-error">{{ error }}</p>
    {% endfor %}

    <!-- {% if form.errors %}
        {% for field, error_list in form.errors.items %}
            {% for error in error_list %}
            <p class="text-danger">{{ error }}</p>
            {%endfor%}
        {% endfor %}
    {%endif%} -->

    {% for field in form %}
        <div class="mb-3">
            <label class="form-label" for="{{ field.id_for_label }}">{{ field.label}}</label>
            {{ field }}
            {% for error in field.errors %}
                <p class="text-danger">{{ error }}</p>
            {% endfor %}
        </div>
    {% endfor %}
</div>
<button type="submit" class="btn btn-primary mt-3 mb-3">{{ button_text }}</button>

templates/partials/footer.html
<footer>
    <section class="footer">
      <div class="container">
        <div class="row">
          <div class="col-md-3 col-6">
            <h4>Информация</h4>
            <ul class="list-unstyled">
              <li><a href="">Главная</a></li>
              <li><a href="">О магазине</a></li>
              <li><a href="">Оплата и доставка</a></li>
              <li><a href="">Контакты</a></li>
            </ul>
          </div>

          <div class="col-md-3 col-6">
            <h4>Время работы</h4>
            <ul class="list-unstyled">
              <li>г. Уральск ул. Достык 41</li>
              <li>9:00 - 18:00</li>
              <li>Без перерыва</li>
            </ul>
          </div>

          <div class="col-md-3 col-6">
            <h4>Контакты</h4>
            <ul class="list-unstyled">
              <li><a href="tel:87777333333">8 (777) 733 33 33</a></li>
              <li><a href="tel:87777333334">8 (777) 733 33 34</a></li>
              <li><a href="tel:87777333335">8 (777) 733 33 35</a></li>
            </ul>
          </div>

          <div class="col-md-3 col-6">
            <h4>МЫ в сети</h4>
            <div class="footer-icons">
              <a href=""><i class="fab fa-facebook-f"></i></a>
              <a href=""><i class="fab fa-youtube"></i></a>
              <a href=""><i class="fab fa-instagram"></i></a>
            </div>
          </div>
        </div>
      </div>
    </section>
</footer>

templates/partials/forms.html
<div class="container my-3">
    <div class="row justify-content-center">
        <div class="col-sm-8 col-lg-6">
            <div class="card">
                <div class="card-header bg-secondary text-white">
                    {{title_text}}
                </div>     
                <div class="p-2">
                    {% if not fields_only%}
                        <form action="{{action_url}}?next={{request.GET.next}}" method="{{form_method}}" enctype="multipart/form-data">
                        {%csrf_token%}
                    {%endif%}
                            {% for error in form.non_field_errors %}
                            <p class="text-danger">{{error}} </p>
                            {%endfor%}

                            {% for field in form %}
                            {{field.label}}
                            {{field}}
                            {% for error in field.errors %}
                            <p class="text-danger">{{error}} </p>
                            {% endfor %}

                            {%endfor%}
                    {% if not fields_only%}
                            <button type="submit" class="btn btn-primary my-3">{{button_text|default:"Обновить"}}</button>
                        </form>
                    {%endif%}
                </div>  
            </div>
        </div>
    </div>
    
</div>

templates/partials/modal_cart.html
{% comment %} {% load static %}
<div class="modal fade" id="modal-cart" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header bg-secondary text-white">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Корзина</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <table class="table">
            <tbody>
              <tr>
                <th scope="row">ID</th>
                <td></td>
                <td>Продукт</td>
                <td>Цена</td>
                <td>Количество</td>
              </tr>
              {% for item in cart %}
              <tr>        
                <th scope="row">{{item.product.id}}</th>
                <td><img src="{{item.product.picture}}" alt="product1"></td>
                <td><a href="{% url 'product_details' item.product.id %}">{{item.product.name}}</a></td>
                <td>{{item.price}}</td>
                <td>{{item.quontity}}</td>
              </tr>
              {%endfor%}
            </tbody>
          </table>
          <p class="total-price">Итого: {{total}}</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Вернуться</button>
          <button type="button" class="btn btn-primary">Оформить заказ</button>
        </div>
      </div>
    </div>
</div> {% endcomment %}

templates/partials/navigation_bar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home_page'%}">My-Shop</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home_page' %}">Категории</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'product_list_all' %}">Продукты</a>
          </li>

          <li class="nav-item">
            {%if perms.my_shop.add_product and request.user.profile.is_approved%}
            <a class="nav-link" href="{% url 'product_create' %}">Добавить продукт</a>
            {%endif%}
          </li>
          <li class="nav-item">
            {%if perms.my_shop.add_category%}
            <a class="nav-link" href="{% url 'category_create' %}">Добавить категорию</a>
            {%endif%}
          </li>
        </ul>
        <div class="menu-links">
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'favorite_list' %}"><i class="fa-solid fa-heart" style="font-size: 18px;"></i></a>
            </li>
            <li class="nav-item dropdown">
              {%if not request.user.profile.is_approved and request.user.is_authenticated %}
              <a class="nav-link dropdown-toggle d-flex-d" data-bs-toggle="dropdown" href="#"><i class="fa-solid fa-user" style="font-size: 18px;"></i>
                (Не подтвержден) {{request.user.username}}</a>
              {%else%}
              <a class="nav-link dropdown-toggle d-flex-d" data-bs-toggle="dropdown" href="#"><i class="fa-solid fa-user" style="font-size: 18px;"></i>
                {{request.user.username}}</a>
              {%endif%}
                <ul class="dropdown-menu">
                  {% if not request.user.is_authenticated %}
                  <li><a class="dropdown-item" href="{% url 'register' 0 %}?next={{request.get_full_path}}">Регистрация Клиента</a></li>
                  <li><a class="dropdown-item" href="{% url 'register' 1 %}?next={{request.get_full_path}}">Регистрация Продавца</a></li>
                  <li><a class="dropdown-item" href="{% url 'login' %}?next={{request.get_full_path}}">Вход</a></li>
                  {%else%}
                  <li><a class="dropdown-item" href="{% url 'user_detail' %}">Кабинет</a></li>
                  <li><a class="dropdown-item" href="{% url 'logout' %}?next={{request.get_full_path}}">Выход</a></li>
                  {%endif%}
                </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'cart_view' %}">
                  <i class="fa-solid fa-cart-shopping position-relative" style="font-size: 18px;"> Корзина
                      {%with cart_qty=cart|length%}
                        {% if cart_qty > 0 %}
                        <span id="cartCount" class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                          {{cart_qty}}
                        </span>
                        {%else%}
                        <span id="cartCount" class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger invisible">
                          {{cart_qty}}
                        </span>
                        {%endif%}
                      {%endwith%}
                  </i>
                  
                </a>
                <!-- <a class="nav-link" href="" data-bs-toggle="modal" data-bs-target="#modal-cart">
                  <i class="fa-solid fa-cart-shopping"></i>
                </a> -->
                <!-- _______Modal-cart_____ -->
                <!-- {% include 'partials/modal_cart.html' %} -->
                <!-- __________Modal-cart________ -->
            </li>
            <li class="nav-item">
                <a class="nav-link" href=""><i class="fa-solid fa-magnifying-glass" style="font-size: 18px;"></i></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
</nav>

templates/partials/pagination.html
<nav aria-label="Page navigation">
    {% if page_obj.paginator.num_pages > 1 %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Назад</a></li>
        {% else %}
      <li class="page-item disabled"><a class="page-link">Назад</a></li>
        {% endif %}
        {% for page in page_obj.paginator %}
      <li class="page-item"><a class="page-link" href="?page={{page.number}}">{{page.number}}</a></li>
        {%endfor%}
        {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Вперед</a></li>
        {% else %}
        <li class="page-item disabled"><a class="page-link">Вперед</a></li>
        {% endif %}
    </ul>
    {% endif %}
</nav>

templates/partials/pagination_search.html
<nav aria-label="Page navigation">
    {% if page_obj.paginator.num_pages > 1 %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?search={{ request.GET.search}}&page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% else %}
      <li class="page-item disabled"><a class="page-link">Previous</a></li>
        {% endif %}
        {% for page in page_obj.paginator %}
      <li class="page-item"><a class="page-link" href="?search={{ request.GET.search}}&page={{page.number}}">{{page.number}}</a></li>
        {%endfor%}
        {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?search={{ request.GET.search}}&page={{ page_obj.next_page_number }}">Next</a></li>
        {% else %}
        <li class="page-item disabled"><a class="page-link">Next</a></li>
        {% endif %}
    </ul>
    {% endif %}
</nav>

templates/partials/user_forms.html
{% if not fields_only%}
    <form action="{{action_url}}" method="{{form_method}}" enctype="multipart/form-data">
    {%csrf_token%}
{%endif%}
        {% for error in form.non_field_errors %}
        <p class="text-danger">{{error}} </p>
        {%endfor%}

        {% for field in form %}
        {{field.label}}
        {{field}}
        {% for error in field.errors %}
        <p class="text-danger">{{error}} </p>
        {% endfor %}

        {%endfor%}
{% if not fields_only%}
        <button type="submit" class="btn btn-primary my-3">{{button_text|default:"Обновить"}}</button>
    </form>
{%endif%}