cart/urls.py
from django.urls import path
from .views import cart_view, cart_update_view, cart_add_view, cart_delete_view, cart_clear_view, comment_update_view

urlpatterns = [
    path('', cart_view, name='cart_view'),
    path('add/', cart_add_view, name='cart_add'),
    path('update/', cart_update_view, name='cart_update'),
    path('delete/', cart_delete_view, name='cart_delete'),
    path('clear/', cart_clear_view, name='cart_clear'),
    path('comment_update/', comment_update_view, name='cart_comment_update'),
]

payments/urls.py
from django.urls import path
from .views import delivery_approve_view, complete_order_view, payment_success_view, payment_fail_view

urlpatterns = [
    path('checkout/', delivery_approve_view, name='delivery_approve'),
    path('complete/', complete_order_view, name='complete_order'),
    path('success/', payment_success_view, name='payment_success'),
    path('fail/', payment_fail_view, name='payment_fail'),
]

source/urls.py
from django.contrib import admin
from django.urls import path, include
from my_shop.views.category_views import IndexView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='home_page'),
    path('products/', include('my_shop.urls.product_urls')),
    path('categories/', include('my_shop.urls.category_urls')),
    path('favorites/', include('my_shop.urls.favorite_urls')),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
    path('payments/', include('payments.urls')),
    path('api/', include('my_shop_api.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from my_shop.models import Product


class Delivery(models.Model):
    user = models.OneToOneField(
        get_user_model(),
        related_name = 'delivery',
        on_delete = models.CASCADE,
        verbose_name = 'Пользователь' 
        )
    city = models.CharField(max_length=100, null=True, blank=True, verbose_name='City')
    street = models.CharField(max_length=100, null=True, blank=True, verbose_name='Street')
    home = models.CharField(max_length=100, null=True, blank=True, verbose_name='Home')
    appart = models.CharField(max_length=100, null=True, blank=True, verbose_name='Appart')
    
    def __str__(self) -> str:
        return f'Город: {self.city}, улица: {self.street}, дом: {self.home}, квартира: {self.appart}'
        
class Profile(models.Model):
    user = models.OneToOneField(
        get_user_model(),
        related_name = 'profile',
        on_delete = models.CASCADE,
        verbose_name = 'Пользователь' 
        )
    phone = models.CharField(max_length=20, null=True, blank=True, verbose_name='Phone')
    avatar = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name='Avatar')
    favorites = models.ManyToManyField(Product, related_name='profile', verbose_name='Favorite')
    is_approved = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.user.get_full_name()

payments/models.py
from django.db import models
from django.contrib.auth import get_user_model
from my_shop.models import Product


class StatusOrder(models.Model):
    status = models.CharField(max_length=100, null=False, blank=False, verbose_name='status')

    def __str__(self):
        return self.status

class StatusOrderItem(models.Model):
    status = models.CharField(max_length=100, null=False, blank=False, verbose_name='status')

    def __str__(self):
        return self.status

class Order(models.Model):
    status = models.ForeignKey(StatusOrder, on_delete=models.PROTECT, related_name='orders', verbose_name='Status')
    total = models.DecimalField(max_digits=10, decimal_places=2, default=0.00, verbose_name='Total')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Created at')
    buyer= models.ForeignKey(get_user_model(), on_delete=models.PROTECT, related_name='orders', verbose_name='Buyer')
    def __str__(self):
        return f'Ордер #{self.pk}; Статус: {self.status.status}'

class OrderItem(models.Model):
    seller = models.ForeignKey(get_user_model(), on_delete=models.PROTECT, related_name='order_items', verbose_name='Seller')
    product = models.ForeignKey(Product, on_delete=models.PROTECT, related_name='order_items', verbose_name='Product')
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='order_items', verbose_name='Order')
    quontity = models.IntegerField(null=False, blank=False, verbose_name='Quontity')
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00, verbose_name='Total price')
    status = models.ForeignKey(StatusOrderItem, on_delete=models.PROTECT, related_name='order_items', verbose_name='Status')

    def __str__(self):
        return f'{self.product.name}; Ордер #{self.order.pk}; Статус: {self.status.status}'
    
class Comment(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.PROTECT, related_name='comments', verbose_name='User')
    text = models.TextField(max_length=1000, null=False, blank=False, verbose_name='Text')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Created at')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Updated at')
    order_item = models.ForeignKey(OrderItem, on_delete=models.CASCADE, related_name='comments', verbose_name='Order item')

    def __str__(self):
        return self.text

payments/views.py
from django.shortcuts import render
from django.views.generic import UpdateView
from accounts.models import Delivery
from accounts.forms import DeliveryEditForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from cart.cart import Cart
from .models import Order, OrderItem, StatusOrder, StatusOrderItem, Comment
from my_shop.models import Product
from django.contrib.auth import get_user_model
from decimal import Decimal


def delivery_approve_view(request):
    if request.method == 'GET':
        form = DeliveryEditForm(instance=Delivery.objects.get(user=request.user))
        return render(request, 'payments/delivery_approve.html', context={'form': form})

def complete_order_view(request):
    if request.method == 'POST':
        delivery = Delivery.objects.get(user=request.user)
        delivery.city = request.POST.get('city')
        delivery.street = request.POST.get('street')
        delivery.home = request.POST.get('home')
        delivery.appart = request.POST.get('appart')
        delivery.save()

        cart_class = Cart(request)
        cart = cart_class.cart
        product_ids = cart.keys()

        order = Order.objects.create(status=StatusOrder.objects.get(status='Открыт'), total=cart_class.get_total_price(), buyer=request.user)

        for product_id in product_ids:
            product = Product.objects.get(id=product_id)
            seller = get_user_model().objects.get(id=product.seller.id)
            quontity = cart[product_id]['quantity']
            price = cart[product_id]['price']
            total_price = quontity * Decimal(price)

            instance = OrderItem.objects.create(
                order=order,
                product=product,
                seller=seller,
                quontity=quontity,
                total_price=total_price,
                status = StatusOrderItem.objects.get(status='В обработке')
            )
            product.quontity -= quontity
            product.save()
            if cart[product_id]['comment'] != '':
                comment =Comment.objects.create(user=request.user, text=cart[product_id]['comment'], order_item=instance)
            
        return JsonResponse({'status': 'success'})

def payment_success_view(request):
    cart = Cart(request)
    cart.clear()
    return render(request, 'payments/payment_success.html')

def payment_fail_view(request):
    return render(request, 'payments/payment_fail.html')

templates/payments/delivery_approve.html
{% extends 'base.html' %}

{%block content%}
<div class="container my-3">
    <div class="row justify-content-center">
        <div class="col-sm-8 col-lg-6">
            <div class="card">
                <div class="card-header bg-secondary text-white">
                    Плдтверждение Адреса Доставки
                </div>     
                <div class="p-2">
                    {% include 'partials/user_forms.html' with form=form fields_only=True %}
                    <button type="submit" id="approve" class="btn btn-primary my-3">Подвердить и Оплатить</button>
                </div>  
            </div>
        </div>
    </div>
</div>
{%endblock%}

{% block script %}
<script>
    $(document).on('click', '#approve', function(e){
        e.preventDefault();
        let city = $('#id_city').val();
        let street = $('#id_street').val();
        let home = $('#id_home').val();
        let appart = $('#id_appart').val();
        console.log(appart);
        $.ajax({
          type: 'POST',
          url: '{% url "complete_order" %}',
          data: {
              csrfmiddlewaretoken: '{{ csrf_token }}',
              city : $('#id_city').val(),
              street : $('#id_street').val(),
              home: $('#id_home').val(),
              appart: $('#id_appart').val(),  
          },
          dataType: 'json',
          success: function(response){
              console.log(response.status);
              window.location.href = "{% url 'payment_success' %}";
          },
          error: function(error, status){
              console.log(error);
              window.location.href = "{% url 'payment_fail' %}";
         }
    })
   }); 
</script>
{%endblock%}

templates/payments/payment_fail.html
{% extends 'base.html' %}

{%block content%}
<h5 class="text-center">Ошибка покупки!</h5>  
{%endblock%}

templates/payments/payment_success.html
{% extends 'base.html' %}

{%block content%}
<h5 class="text-center">Спасибо за покупку!</h5>  
{%endblock%}